### ISSUE TITLE
Failed to send transaction

### ISSUE THREAD

**Issue by UPRLS9000** [kokomoAAA/wax-bot-lib#2]
Hello.
I'm trying to get code like this:
```
const { Wallet } = require("wax-bot-lib");
const { Sender } = require("wax-bot-lib");
const { RpcWrapper } = require("wax-bot-lib");

async function test() {
    const wallet = new Wallet(
        "https://wax.eosphere.io/v2", // api endpoint to use
        {
            address: "your wallet's address", // your wallet's address
            private_key:
                "wallet's private key", // wallet's private key
        }
    );

    wallet.init();

    const sender = new Sender(wallet);

    const contracts = [
        {
            contract_name: "eosio.token", // example
            contract_action: "transfer", // example
            params: {
                from: wallet.executorAddress,
                memo: "",
                quantity: "0.01000000 WAX",
                to: "c2crc.wam",
            },
        },
    ];

    const [res, err] = await sender.sendTx(contracts);
    if (err) console.log(err);
}
test();
```

I get an error in the console:
```
E:\nodejs\test.node>node app.js
E:\nodejs\test.node\node_modules\wax-bot-lib\dist\libs\classes\transactions\reg_tx.js:61
                            console.log(err_1.details[0].message);
                                                     ^

TypeError: Cannot read properties of undefined (reading '0')
    at RegularTransaction.<anonymous> (E:\nodejs\test.node\node_modules\wax-bot-lib\dist\libs\classes\transactions\reg_tx.js:61:54)
    at step (E:\nodejs\test.node\node_modules\wax-bot-lib\dist\libs\classes\transactions\reg_tx.js:33:23)
    at Object.throw (E:\nodejs\test.node\node_modules\wax-bot-lib\dist\libs\classes\transactions\reg_tx.js:14:53)
    at rejected (E:\nodejs\test.node\node_modules\wax-bot-lib\dist\libs\classes\transactions\reg_tx.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.14.2
```

What could be the problem? Help me please.

**Comment by UPRLS9000** [comment]
I have changed the api endpoint to "https://wax.eosphere.io" and now I am getting the error: "A Request body is required"

Help me figure out what I'm doing wrong, please.

My code:
```
const { Wallet } = require("wax-bot-lib");
const { Sender } = require("wax-bot-lib");
const { RpcWrapper } = require("wax-bot-lib");

async function test() {
    const wallet = new Wallet(
        "https://wax.eosphere.io", // api endpoint to use
        {
            address: "your wallet's address", // your wallet's address
            private_key:
                "wallet's private key", // wallet's private key
        }
    );

    wallet.init();

    const sender = new Sender(wallet);

    const contracts = [
        {
            contract_name: "eosio.token", // example
            contract_action: "transfer", // example
            params: {
                from: wallet.executorAddress,
                memo: "",
                quantity: "0.01000000 WAX",
                to: "c2crc.wam",
            },
        },
    ];

    const [res, err] = await sender.sendTx(contracts);
    if (err) console.log(err);
}
test();
```

**Comment by edo-lucio** [comment]
Hi, sorry for the late reply.
Could you tell me which version of the project you are using ?
It doesn't seem you are using the latest one but i could be wrong.
Try installing the package with:

npm install ***@***.***

or

npm install ***@***.***

Again, excuse me for the late reply.
I will happy to help you further if needed


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Privo
di virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno dom 5 mar 2023 alle ore 16:17 UPRLS9000 ***@***.***>
ha scritto:

**Comment by edo-lucio** [comment]
> Hello. I'm trying to get code like this:
> 
> ```
> const { Wallet } = require("wax-bot-lib");
> const { Sender } = require("wax-bot-lib");
> const { RpcWrapper } = require("wax-bot-lib");
> 
> async function test() {
>     const wallet = new Wallet(
>         "https://wax.eosphere.io/v2", // api endpoint to use
>         {
>             address: "your wallet's address", // your wallet's address
>             private_key:
>                 "wallet's private key", // wallet's private key
>         }
>     );
> 
>     wallet.init();
> 
>     const sender = new Sender(wallet);
> 
>     const contracts = [
>         {
>             contract_name: "eosio.token", // example
>             contract_action: "transfer", // example
>             params: {
>                 from: wallet.executorAddress,
>                 memo: "",
>                 quantity: "0.01000000 WAX",
>                 to: "c2crc.wam",
>             },
>         },
>     ];
> 
>     const [res, err] = await sender.sendTx(contracts);
>     if (err) console.log(err);
> }
> test();
> ```
> 
> I get an error in the console:
> 
> ```
> E:\nodejs\test.node>node app.js
> E:\nodejs\test.node\node_modules\wax-bot-lib\dist\libs\classes\transactions\reg_tx.js:61
>                             console.log(err_1.details[0].message);
>                                                      ^
> 
> TypeError: Cannot read properties of undefined (reading '0')
>     at RegularTransaction.<anonymous> (E:\nodejs\test.node\node_modules\wax-bot-lib\dist\libs\classes\transactions\reg_tx.js:61:54)
>     at step (E:\nodejs\test.node\node_modules\wax-bot-lib\dist\libs\classes\transactions\reg_tx.js:33:23)
>     at Object.throw (E:\nodejs\test.node\node_modules\wax-bot-lib\dist\libs\classes\transactions\reg_tx.js:14:53)
>     at rejected (E:\nodejs\test.node\node_modules\wax-bot-lib\dist\libs\classes\transactions\reg_tx.js:6:65)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v18.14.2
> ```
> 
> What could be the problem? Help me please.

Hi, sorry for the late reply. 
Could you tell me which version of the project you are using ? 
It doesn't seem you are using the latest one but i could be wrong. 
Try installing the package with:
 
npm install wax-bot-lib@2.9.1
or 
npm install wax-bot-lib@2.9.0

I will be happy to help you further if needed

**Comment by edo-lucio** [comment]
> I have changed the api endpoint to "https://wax.eosphere.io" and now I am getting the error: "A Request body is required"
> 
> Help me figure out what I'm doing wrong, please.
> 
> My code:
> 
> ```
> const { Wallet } = require("wax-bot-lib");
> const { Sender } = require("wax-bot-lib");
> const { RpcWrapper } = require("wax-bot-lib");
> 
> async function test() {
>     const wallet = new Wallet(
>         "https://wax.eosphere.io", // api endpoint to use
>         {
>             address: "your wallet's address", // your wallet's address
>             private_key:
>                 "wallet's private key", // wallet's private key
>         }
>     );
> 
>     wallet.init();
> 
>     const sender = new Sender(wallet);
> 
>     const contracts = [
>         {
>             contract_name: "eosio.token", // example
>             contract_action: "transfer", // example
>             params: {
>                 from: wallet.executorAddress,
>                 memo: "",
>                 quantity: "0.01000000 WAX",
>                 to: "c2crc.wam",
>             },
>         },
>     ];
> 
>     const [res, err] = await sender.sendTx(contracts);
>     if (err) console.log(err);
> }
> test();
> ```

Found the error, which is due to my bad documentation i guess. 
Here is the working code: 
```
const { Wallet } = require("wax-bot-lib");
const { Sender } = require("wax-bot-lib");
const { RpcWrapper } = require("wax-bot-lib");

const { config } = require("./config");

async function test() {
  const wallet = new Wallet(
    "https://eu.wax.eosrio.io", // api endpoint to use
    {
      address: config.WALLET, // your wallet's address
      private_key: config.PRIVATE_KEY, // wallet's private key
    }
  );

  wallet.init();

  const sender = new Sender(wallet);

  const contracts = [
    {
      account: "eosio.token",
      name: "transfer",
      authorization: [
        {
          actor: wallet.executorAddress,
          permission: "active",
        },
      ],
      data: {
        from: wallet.executorAddress,
        memo: "",
        quantity: "0.01000000 WAX",
        to: "c2crc.wam",
      },
    },
  ];

  const [res, err] = await sender.sendTx(contracts);

  if (err) console.log(err);
}

test();
```
If you notice, the issue was due to "bad" transaction data. Just use the regular one that you would you use with other transactions. Also notice that by setting ``` fuelTx = true ``` as ``` sendTx ``` argument you can get free tx from fuel.  
Let me know if you have any issue :)

**Comment by UPRLS9000** [comment]
I installed version 2.9.1, tried your code but still got "A Request body is required" error.

If I use this code, I get the error "transaction must have at least one authorization":

```
const { Wallet } = require("wax-bot-lib");
const { Sender } = require("wax-bot-lib");
const { RpcWrapper } = require("wax-bot-lib");

const { config } = require("./config");

async function test() {
  const wallet = new Wallet(
    "https://eu.wax.eosrio.io", // api endpoint to use
    {
      address: config.WALLET, // your wallet's address
      private_key: config.PRIVATE_KEY, // wallet's private key
    }
  );

  wallet.init();

  const sender = new Sender(wallet);

  const contracts = 
    {
      account: "eosio.token",
      name: "transfer",
      authorization: [
        {
          actor: wallet.executorAddress,
          permission: "active",
        },
      ],
      data: {
        from: wallet.executorAddress,
        memo: "",
        quantity: "0.01000000 WAX",
        to: "c2crc.wam",
      },
    };

  const [res, err] = await sender.sendTx(contracts);

  if (err) console.log(err);
}

test();
```

The difference is that here I am passing the transaction not as an array, 21 lines.  It still doesn't work for me, even with your example.
Thanks for helping.

**Comment by edo-lucio** [comment]
@UPRLS9000 I've not been able to reproduce your error.
Contrary to what i said before, try install with 

``` npm install wax-bot-lib@latest```

With ``` "wax-bot-lib^3.0.8" ``` and the example code i've sent you before you should be able to send the tx.

**Comment by UPRLS9000** [comment]
Thank you very much for your help and for developing the library, everything started up thanks to you. Tipping will be, thank you!!!!

**Comment by edo-lucio** [comment]
> Thank you very much for your help and for developing the library, everything started up thanks to you. Tipping will be, thank you!!!!

Thank you, i really appreciate :)
